### ISSUE TITLE
Wildcard search for properties on enter

### ISSUE THREAD

**Issue by justingreco** [justingreco/imaps-ng#14]

**Comment by justingreco** [comment]
limit to owner name?  could return too many if every categories searched.  Don't see this needed for address, PIN, REID, or street name.

**Comment by carterius** [comment]
What do you mean by wildcard? In my opinion the search looks great as is w/autocomplete

**Comment by justingreco** [comment]
Was thinking in case someone wanted to just put SMITH and get a list of all the owners named Smith.

**Comment by justingreco** [comment]
Was thinking in case someone wanted to find all the Smiths that own property, they could just type SMITH, hit enter and then all those properties could be selected.  The autocomplete would not allow for that, but I don't know how many people would do searches like that.

**Comment by CarterVickery** [comment]
gotcha. yes I think we do need this for OWNER only

**Comment by justingreco** [comment]
not sure if this is really needed, closing for now
